In [1]:
#differences between numpy and pandas
# loading numpy and panda
import numpy as np
import pandas as pd

In [4]:
#using pandas
df = pd.read_csv("data/P87-S2-Dataset-Basics-Resources/heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
#using numpy
#all values are converted to float
#2-d array representation
data = df.to_numpy()
print(data.dtype,data)

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [11]:
#chnaging value in numpy
#value 63 changed to 0
data[0,0] = 0
print(data.dtype, data)

float64 [[ 0.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [18]:
#copying a particular segment from pandas dataframe to numpy
data = df[["age", "sex", "cp"]]
data2 = data.to_numpy()
print(data2.dtype, data2)

int64 [[63  1  3]
 [37  1  2]
 [41  0  1]
 [56  1  1]
 [57  0  0]
 [57  1  0]
 [56  0  1]
 [44  1  1]
 [52  1  2]
 [57  1  2]
 [54  1  0]
 [48  0  2]
 [49  1  1]
 [64  1  3]
 [58  0  3]
 [50  0  2]
 [58  0  2]
 [66  0  3]
 [43  1  0]
 [69  0  3]
 [59  1  0]
 [44  1  2]
 [42  1  0]
 [61  1  2]
 [40  1  3]
 [71  0  1]
 [59  1  2]
 [51  1  2]
 [65  0  2]
 [53  1  2]
 [41  0  1]
 [65  1  0]
 [44  1  1]
 [54  1  2]
 [51  1  3]
 [46  0  2]
 [54  0  2]
 [54  1  2]
 [65  0  2]
 [65  0  2]
 [51  0  2]
 [48  1  1]
 [45  1  0]
 [53  0  0]
 [39  1  2]
 [52  1  1]
 [44  1  2]
 [47  1  2]
 [53  0  2]
 [53  0  0]
 [51  0  2]
 [66  1  0]
 [62  1  2]
 [44  0  2]
 [63  0  2]
 [52  1  1]
 [48  1  0]
 [45  1  0]
 [34  1  3]
 [57  0  0]
 [71  0  2]
 [54  1  1]
 [52  1  3]
 [41  1  1]
 [58  1  2]
 [35  0  0]
 [51  1  2]
 [45  0  1]
 [44  1  1]
 [62  0  0]
 [54  1  2]
 [51  1  2]
 [29  1  1]
 [51  1  0]
 [43  0  2]
 [55  0  1]
 [51  1  2]
 [59  1  1]
 [52  1  1]
 [58  1  2]
 [41  1  2]
 [45  1  1]
 [60  0  2

In [19]:
#changing the values with 2-d array acess
data2[0,0] = 2
print(data2.dtype, data2)

int64 [[ 2  1  3]
 [37  1  2]
 [41  0  1]
 [56  1  1]
 [57  0  0]
 [57  1  0]
 [56  0  1]
 [44  1  1]
 [52  1  2]
 [57  1  2]
 [54  1  0]
 [48  0  2]
 [49  1  1]
 [64  1  3]
 [58  0  3]
 [50  0  2]
 [58  0  2]
 [66  0  3]
 [43  1  0]
 [69  0  3]
 [59  1  0]
 [44  1  2]
 [42  1  0]
 [61  1  2]
 [40  1  3]
 [71  0  1]
 [59  1  2]
 [51  1  2]
 [65  0  2]
 [53  1  2]
 [41  0  1]
 [65  1  0]
 [44  1  1]
 [54  1  2]
 [51  1  3]
 [46  0  2]
 [54  0  2]
 [54  1  2]
 [65  0  2]
 [65  0  2]
 [51  0  2]
 [48  1  1]
 [45  1  0]
 [53  0  0]
 [39  1  2]
 [52  1  1]
 [44  1  2]
 [47  1  2]
 [53  0  2]
 [53  0  0]
 [51  0  2]
 [66  1  0]
 [62  1  2]
 [44  0  2]
 [63  0  2]
 [52  1  1]
 [48  1  0]
 [45  1  0]
 [34  1  3]
 [57  0  0]
 [71  0  2]
 [54  1  1]
 [52  1  3]
 [41  1  1]
 [58  1  2]
 [35  0  0]
 [51  1  2]
 [45  0  1]
 [44  1  1]
 [62  0  0]
 [54  1  2]
 [51  1  2]
 [29  1  1]
 [51  1  0]
 [43  0  2]
 [55  0  1]
 [51  1  2]
 [59  1  1]
 [52  1  1]
 [58  1  2]
 [41  1  2]
 [45  1  1]
 [60  0  2

In [25]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [29]:
#changing value in pandas dataframe
#returns 1-d array
df.age.to_numpy()
df.age.to_numpy()[0] = 36;

In [30]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   36    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [36]:
#mean quantile pandas
print(df[["age"]].mean())
print(df[["age"]].quantile())

age    54.277228
dtype: float64
age    55.0
Name: 0.5, dtype: float64


In [40]:
#mean reshape numpy
print(df["age"].to_numpy().mean())
#reshape in 3 rows and any number of columns
print(df["age"].to_numpy().reshape(3,-1))

54.277227722772274
[[36 37 41 56 57 57 56 44 52 57 54 48 49 64 58 50 58 66 43 69 59 44 42 61
  40 71 59 51 65 53 41 65 44 54 51 46 54 54 65 65 51 48 45 53 39 52 44 47
  53 53 51 66 62 44 63 52 48 45 34 57 71 54 52 41 58 35 51 45 44 62 54 51
  29 51 43 55 51 59 52 58 41 45 60 52 42 67 68 46 54 58 48 57 52 54 45 53
  62 52 43 53 42]
 [59 63 42 50 68 69 45 50 50 64 57 64 43 55 37 41 56 46 46 64 59 41 54 39
  34 47 67 52 74 54 49 42 41 41 49 60 62 57 64 51 43 42 67 76 70 44 60 44
  42 66 71 64 66 39 58 47 35 58 56 56 55 41 38 38 67 67 62 63 53 56 48 58
  58 60 40 60 64 43 57 55 65 61 58 50 44 60 54 50 41 51 58 54 60 60 59 46
  67 62 65 44 60]
 [58 68 62 52 59 60 49 59 57 61 39 61 56 43 62 63 65 48 63 55 65 56 54 70
  62 35 59 64 47 57 55 64 70 51 58 60 77 35 70 59 64 57 56 48 56 66 54 69
  51 43 62 67 59 45 58 50 62 38 66 52 53 63 54 66 55 49 54 56 46 61 67 58
  47 52 58 57 58 61 42 52 59 40 61 46 59 57 57 55 61 58 58 67 44 63 63 59
  57 45 68 57 57]]
